version: '3'

services:
  app:
    build:
      context: .docker/app
      dockerfile: Dockerfile
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      XDEBUG_CONFIG: remote_host=${XDEBUG_REMOTE_HOST}
      PHP_IDE_CONFIG: serverName=xdebug-docker
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - portal-network

  web:
    image: nginx:alpine
    tty: true
    working_dir: /var/www
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - portal-network

  db:
    image: postgres:alpine
    tty: true
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      SERVICE_NAME: postgres
      TZ: 'America/Sao_Paulo'
    networks:
      - portal-network

#Docker Networks
networks:
  portal-network:
    driver: bridge
